### ISSUE TITLE
[UE] Bug: 使用nodejs，无法在vscode中输出打印消息

### ISSUE THREAD

**Issue by shuizhujianpan** [Tencent/puerts#1462]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.4

### UE的版本 | UE Version

5.1.1

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

使用nodejs，无法在vscode中输出打印消息

### 问题重现 | Bug reproduce

使用nodejs，可以在vscode中进入断点，但是看不到console.log的打印消息，在unreal编辑器中能看到打印；
切换v8，则能正常进入断点及看到打印消息
```[tasklist]
### Tasks
```

**Comment by shuizhujianpan** [comment]
平台写错了，实际是在windows平台下

**Comment by chexiongsheng** [comment]
处理都一样，通过调用原生的console来实现输出到调试器：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Content/JavaScript/puerts/log.js#L35
唯一解释就是nodejs的原生console不支持

**Comment by shuizhujianpan** [comment]
@chexiongsheng 应该是nodejs16库的问题，将EasyEditorPluginDemo项目下的nodejs库替换到现有项目下，就能正常打印了
