### ISSUE TITLE
[Unity] Bug: When installed through OpenUPM, many files in PuerTS package are missing .meta files

### ISSUE THREAD

**Issue by DoctorGester** [Tencent/puerts#1844]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.1.0

### Unity的版本 | Unity Version

2023.1.13f1

### 发生在哪个平台 | Platform

Editor(mac)

### 错误信息 | Error Message

<img width="1248" alt="image" src="https://github.com/user-attachments/assets/d0ab131f-7089-444c-ba0e-d6944cd464d9">

### 问题重现 | Bug reproduce

Install through https://puerts.github.io/en/docs/puerts/unity/install/#add-from-openupm--available-in-2018

Wait for asset database refresh

Look into console for warnings/errors

**Comment by chexiongsheng** [comment]
try 2.1.0-f2?

**Comment by DoctorGester** [comment]
Yep, looks good now!
