### ISSUE TITLE
[UE] Bug: 编辑器器下正常，打包后静态函数调用报函数为空

### ISSUE THREAD

**Issue by luzhaosama** [Tencent/puerts#1882]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.5

### UE的版本 | UE Version

5.4.4

### 发生在哪个平台 | Platform

win

### 错误信息 | Error Message

V8里，部分静态方法名称大小写改变，例如UKismetMathLibrary::Atan，在遍历输出库里所有的方法以后，变成了atan。
![image](https://github.com/user-attachments/assets/08d033f6-90c3-475e-b819-d94842ccd9db)

### 问题重现 | Bug reproduce

编写如下方法，然后打PC包
![image](https://github.com/user-attachments/assets/b6801d2e-f303-42c0-9e6b-5e6ff8b0d770)
会看到这些log
![image](https://github.com/user-attachments/assets/e8dcc4b3-df83-45e5-bdde-f629e8ff5408)
![image](https://github.com/user-attachments/assets/c40567b5-a767-4cda-8ef9-763a24e2fe76)
红色部分是大小写发生改变的地方

```[tasklist]
### Tasks
```

**Comment by luzhaosama** [comment]
提交一个运行时的报错
![image](https://github.com/user-attachments/assets/4e0928ac-df34-42cc-984f-8559180d629f)

**Comment by chexiongsheng** [comment]
打包后ue的FName默认不区分大小写，这个FName 转字符串是什么样取决于它第一次构造时用的是哪个字符串。

v8的成员函数和属性支持自动规避如上特性，但静态函数和变量尚未支持。

可以用proxy来规避这问题，在这里略微修改下：
https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Content/JavaScript/puerts/uelazyload.js#L18

改为
```
    function getFName(str) {
        // !!我这里写死了只是简单的测试下效果，实际上得到UE那先转FName，然后ToString回传
        return 'clamp';
    }
    
    function FNameCaseFix(cls) {
        let proxy = new Proxy(cls, {
            get: function(cls, name) {
                let m = cls[getFName(name)]; 
                Object.defineProperty(cls, name, {
                    value: m,
                    writable: false,
                    configurable: true,
                    enumerable: false,
                });
                return m;
            }
        });
        Object.setPrototypeOf(cls, proxy);
        return cls;
    }

    let UE = new Proxy(cache, {
        get : function(classWrapers, name)
        {
            let value = classWrapers[name];
            if (value === undefined)
            {
                value = loadUEType(name);
                classWrapers[name] = FNameCaseFix(value);
            }
            return value;
        }
    });
```

**Comment by chexiongsheng** [comment]
上面的修正代码改为Object.getOwnPropertyDescriptor后，然后Object.defineProperty会比较好些

**Comment by rhm0325** [comment]
QuickJs 里的成员变量和成员函数 都可以用类似上面的思路来修改吗

**Comment by chexiongsheng** [comment]
> QuickJs 里的成员变量和成员函数 都可以用类似上面的思路来修改吗

可以的。

**Comment by luzhaosama** [comment]
> 上面的修正代码改为Object.getOwnPropertyDescriptor后，然后Object.defineProperty会比较好些

如果一个类里有两个同名但是大小写不一致的成员，可能也会出现获取错误的问题。但是目前的方案已经能保底了，可以使用，期待有一个更稳妥的方案。

**Comment by chexiongsheng** [comment]
> > 上面的修正代码改为Object.getOwnPropertyDescriptor后，然后Object.defineProperty会比较好些
> 
> 如果一个类里有两个同名但是大小写不一致的成员，可能也会出现获取错误的问题。但是目前的方案已经能保底了，可以使用，期待有一个更稳妥的方案。

这种自己加个静态绑定声明可以解决。
